services:
  - type: web
    name: mern-task-dashboard-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        scope: all

  - type: static
    name: mern-task-dashboard-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mern-task-dashboard-backend.onrender.com/api
